### ISSUE TITLE
yahoo api issues

### ISSUE THREAD

**Issue by almartin82** [almartin82/yahoo_roster_extract#2]
per a bunch of [threads](https://forums.yahoo.net/t5/Help-with-Fantasy-Baseball/Receiving-500-quot-Internal-Server-Error-quot-from-Yahoo-Fantasy/td-p/341427/page/5) on the yahoo forums, the yahoo api is having a lot of issues.  commenters suggest using OAuth 2, but I believe that I'm already hitting that endpoint?

**Comment by almartin82** [comment]
```
OrderedDict([(u'yahoo:error', OrderedDict([(u'@xmlns:yahoo', u'http://yahooapis.com/v1/base.rng'), (u'@xml:lang', u'en-US'), (u'yahoo:description', u'Internal server error')]))])
```

**Comment by almartin82** [comment]
Ok, so the issue here was that Yahoo killed support for OAuth 1.0.  This script used OAuth 1 flow (the 'v2' was yahoo's 2nd implementation, not OAuth2).

Moved everything over to OAuth2 using @josuebrunel's [yahoo_oauth] library and nuked like 50 lines of code.  Thanks, Josue!

Also had to move all of the urls to `https`.

**Comment by josuebrunel** [comment]
> Ok, so the issue here was that Yahoo killed support for OAuth 1.0. This script used OAuth 1 flow (the 'v2' was yahoo's 2nd implementation, not OAuth2).

That's good to know.

>Moved everything over to OAuth2 using @josuebrunel's [yahoo_oauth] library and nuked like 50 lines of code. Thanks, Josue!

@almartin82 you're welcome buddy.
